# Generated by Django 5.0.1 on 2024-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
