# Generated by Django 5.0.1 on 2024-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="course",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
