# Generated by Django 5.0.1 on 2024-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="course",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
