# Generated by Django 5.0.1 on 2024-04-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0009_remove_subcourse_instructor_and_more"),
        ("users", "0009_alter_customuser_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="course",
        ),
        migrations.AddField(
            model_name="customuser",
            name="courses_enrolled",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="instructor.course"
            ),
        ),
    ]
