# Generated by Django 4.2.2 on 2024-05-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_usercourses'),
        ('users', '0011_rename_courses_enrolled_customuser_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
        migrations.AddField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='instructor.usercourses'),
            preserve_default=False,
        ),
    ]
