# Generated by Django 4.2.2 on 2024-05-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_usercourses'),
        ('users', '0012_remove_customuser_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='instructor.usercourses'),
        ),
    ]
