# Generated by Django 5.0.1 on 2024-05-24 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_customuser_enrolled_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="enrolled_courses",
        ),
    ]
