# Generated by Django 5.0.1 on 2024-05-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0017_alter_usercourses_course_alter_usercourses_student"),
        ("users", "0014_remove_customuser_enrolled_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enrolled_courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_users",
                to="instructor.usercourses",
            ),
        ),
    ]
