# Generated by Django 5.0.1 on 2024-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminzira", "0002_maincourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
