# Generated by Django 5.0.1 on 2024-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminzira", "0004_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincourse",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
