# Generated by Django 5.0.1 on 2024-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminzira", "0005_maincourse_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maincourse",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/images/"),
        ),
    ]
