# Generated by Django 5.0.1 on 2024-04-24 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminzira", "0006_alter_maincourse_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maincourse",
            name="category",
        ),
    ]
