# Generated by Django 5.0.1 on 2024-04-24 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminzira", "0007_remove_maincourse_category"),
        ("instructor", "0009_remove_subcourse_instructor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainCourse",
        ),
    ]
