# Generated by Django 5.0.1 on 2024-04-12 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentdetails",
            name="user",
        ),
    ]
