# Generated by Django 5.0.1 on 2024-04-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_paymentdetails_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetails",
            name="payment_status",
            field=models.CharField(max_length=20),
        ),
    ]
