# Generated by Django 5.0.1 on 2024-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_paymentdetails_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="payment_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
