# Generated by Django 5.0.1 on 2024-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_paymentdetails_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="course_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentdetails",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
