# Generated by Django 5.0.1 on 2024-04-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0008_remove_chapter_thumbnail_and_more"),
        ("payment", "0006_paymentdetails_course_id_alter_paymentdetails_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentdetails",
            name="course_id",
        ),
        migrations.AddField(
            model_name="paymentdetails",
            name="course",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="instructor.subcourse",
            ),
            preserve_default=False,
        ),
    ]
