# Generated by Django 5.0.1 on 2024-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0002_remove_course_category_remove_course_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
