# Generated by Django 5.0.1 on 2024-02-25 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0003_course_image_course_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="video_url",
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "avi", "mkv"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/images/"),
        ),
    ]
