# Generated by Django 5.0.1 on 2024-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0005_course_is_active_alter_course_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
