# Generated by Django 5.0.1 on 2024-03-30 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0007_subcourse_chapter_delete_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="subcourse",
            name="preview_video",
        ),
        migrations.RemoveField(
            model_name="subcourse",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="subcourse",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "avi", "mkv"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subcourse",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/images/"),
        ),
    ]
