# Generated by Django 5.0.1 on 2024-04-24 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminzira", "0007_remove_maincourse_category"),
        ("instructor", "0008_remove_chapter_thumbnail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcourse",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="subcourse",
            name="main_course",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="sub_course",
        ),
        migrations.RenameField(
            model_name="chapter",
            old_name="chapter_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="chapter",
            name="preview_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/preview_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "avi", "mkv"])
                ],
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("malayalam", "Malayalam"),
                            ("tamil", "Tamil"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "course_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminzira.category",
                    ),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        related_name="courses_taught", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="instructor.course",
            ),
            preserve_default=False,
        ),
    ]
