# Generated by Django 5.0.1 on 2024-04-24 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0009_remove_subcourse_instructor_and_more"),
        ("payment", "0008_alter_paymentdetails_course_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubCourse",
        ),
    ]
