# Generated by Django 5.0.1 on 2024-04-24 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0010_delete_subcourse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_status",
            new_name="status",
        ),
    ]
