# Generated by Django 5.0.1 on 2024-04-25 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0013_remove_course_instructors_course_instructors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="instructors",
            new_name="instructor",
        ),
    ]
