# Generated by Django 4.2.2 on 2024-05-24 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0015_usercourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='courses',
        ),
        migrations.AddField(
            model_name='usercourses',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='students_enrolled', to='instructor.course', verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
