# Generated by Django 5.0.1 on 2024-05-25 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0017_alter_usercourses_course_alter_usercourses_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="preview_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "avi", "mkv"])
                ],
            ),
        ),
    ]
